# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Cloud-native geospatial data cube workflows with open-source tools
author: Emma Marshall
copyright: "2025" #, Emma Marshall
#logo: logo.png

collapse_inactive_sections: true
#only want to include files listed in toc
only_build_toc_files: false


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks:  'auto'

  allow_errors: true
  timeout: 1500
  exclude_patterns:
  # Can't control execution order in jb build, so be sure to download from zenodo first
    - 'download_zenodo*'


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - "book_refs.bib"

# Information about where the book exists on the web
repository:
  url: https://github.com/e-marshall/cloud-open-source-geospatial-data-cube-workflows
  branch: main  

launch_buttons:
  #binderhub_url: "https://mybinder.org"
  notebook_interface: "jupyterlab"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false

  announcement: >
    🚧 March 2025 - This book is under construction! 🚧


parse:
  myst_enable_extensions:
    - substitution
sphinx:
  config:
    # application/vnd.holoviews_load.v0+json, application/vnd.holoviews_exec.v0+json
    suppress_warnings: ["mystnb.unknown_mime_type"]
    bibtex_reference_style: label
    #citation_style: apa.csl
    myst_heading_anchors: 3
    myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

    myst_substitutions:

      #global nb sections
      break: "----"

# Not sure why but uncommenting these causes all of the md 
# substitution variables and formatting like tabs to not work
#sphinx:
#  extra_extensions:
#    - sphinx_design
#  - sphinxext.opengraph
#  config:
#    ogp_site_url: "file:///home/emmamarshall/Desktop/phd_research/ch1/cloud_os_geospatial_datacube_workflows/book/_build/html/introduction.html"
#    ogp_image: "https://e-marshall.github.io/itslive/_static/itslive_explore_img.png"
#    ogp_description_length: 200
